# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.configureondemand=true
org.gradle.parallel=true
org.gradle.caching=true

group=daves-potioneering
version=12
# Minecraft
minecraft_version=1.21.1

# Dependencies
geckolib=4.7.6

## Fabric
modmenu_version=7.2.2
cloth_config_version=15.0.140

# TODO Enable when fully working
# org.gradle.configuration-cache=true
# org.gradle.unsafe.isolated-projects=true
